language: go

go:
  - 1.12.x

services:
  - docker

env:
  - GO111MODULE=on

install: true

script:
  - make lint
  - make test.unit
  - make build
  - make terraform.chkfmt
  - make terraform.init
  - make terraform.keygen
  - make terraform.validate
  - make terraform.apply
  - make test.e2e
  - make terraform.destroy
