language: go

go:
  - 1.12.x

services:
  - docker

env:
  - GO111MODULE=on GOLANGCI_LINT_VER=1.16.0

install: true

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v${GOLANGCI_LINT_VER}

script:
  - make lint
  - make test
  - make build
  - make terraform.keygen
  - make terraform.init
  - make terraform.chkfmt
  - make terraform.validate
