language: go

go:
  - 1.12.x

env:
  - GOLANGCI-LINT_VER=1.16.0
  - TERRAFORM_VER=0.11.13
  - GO111MODULE=on

install: true

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v${GOLANGCI-LINT_VER}
  - curl --silent --output terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VER}/terraform_${TERRAFORM_VER}_linux_amd64.zip
  - unzip terraform.zip ; rm -f terraform.zip; chmod +x terraform
  - mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin; mv terraform ${HOME}/bin/
  - terraform -v

script:
  - make lint
  - make test
  - cd terraform
  - terraform init
  - terraform fmt -check=true
  - terraform validate
