language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

install: true

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

script:
  - golangci-lint run --no-config --skip-dirs "pkg/(client|models|restapi)" --disable unused
  - go test -v -race ./...
  #- cd test && godog -f progress
