// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Payments API
Payments API as specified in Form3 take home test


    Schemes:
      http
    Host: api.example.com
    BasePath: /v1
    Version: 1

    Consumes:
    - application/vnd.api+json

    Produces:
    - application/vnd.api+json

swagger:meta
*/
package restapi
