apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: papi
    tier: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: papi
    tier: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: papi
spec:
  selector:
    matchLabels:
      app: papi
      tier: db
  replicas: 1
  template:
    metadata:
      labels:
        app: papi
        tier: db
    spec:
      containers:
        - name: db
          image: postgres:11.3-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-config
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: papi
    tier: backend
spec:
  ports:
    - port: 8080
  selector:
    app: papi
    tier: backend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: papi
spec:
  selector:
    matchLabels:
      app: papi
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: papi
        tier: backend
    spec:
      containers:
        - name: server
          image: volmedo/papi:test
          imagePullPolicy: Always
          args:
            [
              "-port=8080",
              "-dbhost=db",
              "-dbport=5432",
              "-dbuser=papi_user",
              "-dbpass=p4p1_p455",
              "-dbname=papi_db",
            ]
          ports:
            - containerPort: 8080
