apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: papi
    tier: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: papi
    tier: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: papi
spec:
  selector:
    matchLabels:
      app: papi
      tier: db
  replicas: 1
  template:
    metadata:
      labels:
        app: papi
        tier: db
    spec:
      containers:
        - name: db
          image: postgres:11.3-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: pass
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: papi
    tier: backend
spec:
  ports:
    - port: 8080
  selector:
    app: papi
    tier: backend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: papi
spec:
  selector:
    matchLabels:
      app: papi
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: papi
        tier: backend
    spec:
      containers:
        - name: server
          image: volmedo/papi:test
          imagePullPolicy: Always
          env:
            - name: PAPI_PORT
              value: "8080"
            - name: PAPI_DBHOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: PAPI_DBPORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: port
            - name: PAPI_DBUSER
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: user
            - name: PAPI_DBPASS
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: pass
            - name: PAPI_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbname
          ports:
            - containerPort: 8080
