// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// AccountNumber Account number
// swagger:model AccountNumber
type AccountNumber string

// Validate validates this account number
func (m AccountNumber) Validate(formats strfmt.Registry) error {
	return nil
}
