// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/volmedo/pAPI/pkg/models"
)

// CreatePaymentReader is a Reader for the CreatePayment structure.
type CreatePaymentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreatePaymentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreatePaymentCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewCreatePaymentConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewCreatePaymentTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewCreatePaymentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreatePaymentCreated creates a CreatePaymentCreated with default headers values
func NewCreatePaymentCreated() *CreatePaymentCreated {
	return &CreatePaymentCreated{}
}

/*CreatePaymentCreated handles this case with default header values.

Payment created successfully
*/
type CreatePaymentCreated struct {
	Payload *models.PaymentCreationResponse
}

func (o *CreatePaymentCreated) Error() string {
	return fmt.Sprintf("[POST /payments][%d] createPaymentCreated  %+v", 201, o.Payload)
}

func (o *CreatePaymentCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaymentCreationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePaymentConflict creates a CreatePaymentConflict with default headers values
func NewCreatePaymentConflict() *CreatePaymentConflict {
	return &CreatePaymentConflict{}
}

/*CreatePaymentConflict handles this case with default header values.

A payment with the given ID already exists
*/
type CreatePaymentConflict struct {
	Payload *models.APIError
}

func (o *CreatePaymentConflict) Error() string {
	return fmt.Sprintf("[POST /payments][%d] createPaymentConflict  %+v", 409, o.Payload)
}

func (o *CreatePaymentConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePaymentTooManyRequests creates a CreatePaymentTooManyRequests with default headers values
func NewCreatePaymentTooManyRequests() *CreatePaymentTooManyRequests {
	return &CreatePaymentTooManyRequests{}
}

/*CreatePaymentTooManyRequests handles this case with default header values.

Too Many Requests
*/
type CreatePaymentTooManyRequests struct {
}

func (o *CreatePaymentTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /payments][%d] createPaymentTooManyRequests ", 429)
}

func (o *CreatePaymentTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreatePaymentInternalServerError creates a CreatePaymentInternalServerError with default headers values
func NewCreatePaymentInternalServerError() *CreatePaymentInternalServerError {
	return &CreatePaymentInternalServerError{}
}

/*CreatePaymentInternalServerError handles this case with default header values.

Internal Server Error
*/
type CreatePaymentInternalServerError struct {
	Payload *models.APIError
}

func (o *CreatePaymentInternalServerError) Error() string {
	return fmt.Sprintf("[POST /payments][%d] createPaymentInternalServerError  %+v", 500, o.Payload)
}

func (o *CreatePaymentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
