// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeletePaymentParams creates a new DeletePaymentParams object
// with the default values initialized.
func NewDeletePaymentParams() *DeletePaymentParams {
	var ()
	return &DeletePaymentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePaymentParamsWithTimeout creates a new DeletePaymentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeletePaymentParamsWithTimeout(timeout time.Duration) *DeletePaymentParams {
	var ()
	return &DeletePaymentParams{

		timeout: timeout,
	}
}

// NewDeletePaymentParamsWithContext creates a new DeletePaymentParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeletePaymentParamsWithContext(ctx context.Context) *DeletePaymentParams {
	var ()
	return &DeletePaymentParams{

		Context: ctx,
	}
}

// NewDeletePaymentParamsWithHTTPClient creates a new DeletePaymentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeletePaymentParamsWithHTTPClient(client *http.Client) *DeletePaymentParams {
	var ()
	return &DeletePaymentParams{
		HTTPClient: client,
	}
}

/*DeletePaymentParams contains all the parameters to send to the API endpoint
for the delete payment operation typically these are written to a http.Request
*/
type DeletePaymentParams struct {

	/*ID
	  ID of payment to delete

	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete payment params
func (o *DeletePaymentParams) WithTimeout(timeout time.Duration) *DeletePaymentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete payment params
func (o *DeletePaymentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete payment params
func (o *DeletePaymentParams) WithContext(ctx context.Context) *DeletePaymentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete payment params
func (o *DeletePaymentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete payment params
func (o *DeletePaymentParams) WithHTTPClient(client *http.Client) *DeletePaymentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete payment params
func (o *DeletePaymentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete payment params
func (o *DeletePaymentParams) WithID(id strfmt.UUID) *DeletePaymentParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete payment params
func (o *DeletePaymentParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePaymentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
