// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/volmedo/pAPI/pkg/models"
)

// ListPaymentsReader is a Reader for the ListPayments structure.
type ListPaymentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListPaymentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListPaymentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewListPaymentsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewListPaymentsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewListPaymentsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListPaymentsOK creates a ListPaymentsOK with default headers values
func NewListPaymentsOK() *ListPaymentsOK {
	return &ListPaymentsOK{}
}

/*ListPaymentsOK handles this case with default header values.

List of payment details
*/
type ListPaymentsOK struct {
	Payload *models.PaymentDetailsListResponse
}

func (o *ListPaymentsOK) Error() string {
	return fmt.Sprintf("[GET /payments][%d] listPaymentsOK  %+v", 200, o.Payload)
}

func (o *ListPaymentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaymentDetailsListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPaymentsNotFound creates a ListPaymentsNotFound with default headers values
func NewListPaymentsNotFound() *ListPaymentsNotFound {
	return &ListPaymentsNotFound{}
}

/*ListPaymentsNotFound handles this case with default header values.

The query returned no payments
*/
type ListPaymentsNotFound struct {
	Payload *models.APIError
}

func (o *ListPaymentsNotFound) Error() string {
	return fmt.Sprintf("[GET /payments][%d] listPaymentsNotFound  %+v", 404, o.Payload)
}

func (o *ListPaymentsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPaymentsTooManyRequests creates a ListPaymentsTooManyRequests with default headers values
func NewListPaymentsTooManyRequests() *ListPaymentsTooManyRequests {
	return &ListPaymentsTooManyRequests{}
}

/*ListPaymentsTooManyRequests handles this case with default header values.

Too Many Requests
*/
type ListPaymentsTooManyRequests struct {
}

func (o *ListPaymentsTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /payments][%d] listPaymentsTooManyRequests ", 429)
}

func (o *ListPaymentsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListPaymentsInternalServerError creates a ListPaymentsInternalServerError with default headers values
func NewListPaymentsInternalServerError() *ListPaymentsInternalServerError {
	return &ListPaymentsInternalServerError{}
}

/*ListPaymentsInternalServerError handles this case with default header values.

Internal Server Error
*/
type ListPaymentsInternalServerError struct {
	Payload *models.APIError
}

func (o *ListPaymentsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /payments][%d] listPaymentsInternalServerError  %+v", 500, o.Payload)
}

func (o *ListPaymentsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
