// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/volmedo/pAPI/pkg/models"
)

// ListPaymentsReader is a Reader for the ListPayments structure.
type ListPaymentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListPaymentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListPaymentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewListPaymentsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewListPaymentsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListPaymentsOK creates a ListPaymentsOK with default headers values
func NewListPaymentsOK() *ListPaymentsOK {
	return &ListPaymentsOK{}
}

/*ListPaymentsOK handles this case with default header values.

List of payment details
*/
type ListPaymentsOK struct {
	Payload *models.PaymentDetailsListResponse
}

func (o *ListPaymentsOK) Error() string {
	return fmt.Sprintf("[GET /payments][%d] listPaymentsOK  %+v", 200, o.Payload)
}

func (o *ListPaymentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaymentDetailsListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPaymentsBadRequest creates a ListPaymentsBadRequest with default headers values
func NewListPaymentsBadRequest() *ListPaymentsBadRequest {
	return &ListPaymentsBadRequest{}
}

/*ListPaymentsBadRequest handles this case with default header values.

Bad Request
*/
type ListPaymentsBadRequest struct {
	Payload *models.APIError
}

func (o *ListPaymentsBadRequest) Error() string {
	return fmt.Sprintf("[GET /payments][%d] listPaymentsBadRequest  %+v", 400, o.Payload)
}

func (o *ListPaymentsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPaymentsInternalServerError creates a ListPaymentsInternalServerError with default headers values
func NewListPaymentsInternalServerError() *ListPaymentsInternalServerError {
	return &ListPaymentsInternalServerError{}
}

/*ListPaymentsInternalServerError handles this case with default header values.

Internal Server Error
*/
type ListPaymentsInternalServerError struct {
	Payload *models.APIError
}

func (o *ListPaymentsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /payments][%d] listPaymentsInternalServerError  %+v", 500, o.Payload)
}

func (o *ListPaymentsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
