// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"net/url"

	"github.com/go-openapi/runtime"
	rtclient "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/volmedo/pAPI/pkg/client/payments"
)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.example.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/v1"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

type Config struct {
	// URL is the base URL of the upstream server
	URL *url.URL
	// Transport is an inner transport for the client
	Transport http.RoundTripper
	// AuthInfo is for authentication
	AuthInfo runtime.ClientAuthInfoWriter
}

// New creates a new payments HTTP client.
func New(c Config) *Payments {
	var (
		host     = DefaultHost
		basePath = DefaultBasePath
		schemes  = DefaultSchemes
	)

	if c.URL != nil {
		host = c.URL.Host
		basePath = c.URL.Path
		schemes = []string{c.URL.Scheme}
	}

	transport := rtclient.New(host, basePath, schemes)
	transport.Consumers["application/vnd.api+json"] = runtime.JSONConsumer()
	transport.Producers["application/vnd.api+json"] = runtime.JSONProducer()
	if c.Transport != nil {
		transport.Transport = c.Transport
	}

	cli := new(Payments)
	cli.Transport = transport
	cli.Payments = payments.New(transport, strfmt.Default, c.AuthInfo)
	return cli
}

// Payments is a client for payments
type Payments struct {
	Payments  *payments.Client
	Transport runtime.ClientTransport
}
