// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/volmedo/pAPI/pkg/models"
)

// GetPaymentOKCode is the HTTP code returned for type GetPaymentOK
const GetPaymentOKCode int = 200

/*GetPaymentOK Payment details

swagger:response getPaymentOK
*/
type GetPaymentOK struct {

	/*
	  In: Body
	*/
	Payload *models.PaymentDetailsResponse `json:"body,omitempty"`
}

// NewGetPaymentOK creates GetPaymentOK with default headers values
func NewGetPaymentOK() *GetPaymentOK {

	return &GetPaymentOK{}
}

// WithPayload adds the payload to the get payment o k response
func (o *GetPaymentOK) WithPayload(payload *models.PaymentDetailsResponse) *GetPaymentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get payment o k response
func (o *GetPaymentOK) SetPayload(payload *models.PaymentDetailsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPaymentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPaymentNotFoundCode is the HTTP code returned for type GetPaymentNotFound
const GetPaymentNotFoundCode int = 404

/*GetPaymentNotFound Payment Not Found

swagger:response getPaymentNotFound
*/
type GetPaymentNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetPaymentNotFound creates GetPaymentNotFound with default headers values
func NewGetPaymentNotFound() *GetPaymentNotFound {

	return &GetPaymentNotFound{}
}

// WithPayload adds the payload to the get payment not found response
func (o *GetPaymentNotFound) WithPayload(payload *models.APIError) *GetPaymentNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get payment not found response
func (o *GetPaymentNotFound) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPaymentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPaymentTooManyRequestsCode is the HTTP code returned for type GetPaymentTooManyRequests
const GetPaymentTooManyRequestsCode int = 429

/*GetPaymentTooManyRequests Too Many Requests

swagger:response getPaymentTooManyRequests
*/
type GetPaymentTooManyRequests struct {
}

// NewGetPaymentTooManyRequests creates GetPaymentTooManyRequests with default headers values
func NewGetPaymentTooManyRequests() *GetPaymentTooManyRequests {

	return &GetPaymentTooManyRequests{}
}

// WriteResponse to the client
func (o *GetPaymentTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(429)
}

// GetPaymentInternalServerErrorCode is the HTTP code returned for type GetPaymentInternalServerError
const GetPaymentInternalServerErrorCode int = 500

/*GetPaymentInternalServerError Internal Server Error

swagger:response getPaymentInternalServerError
*/
type GetPaymentInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetPaymentInternalServerError creates GetPaymentInternalServerError with default headers values
func NewGetPaymentInternalServerError() *GetPaymentInternalServerError {

	return &GetPaymentInternalServerError{}
}

// WithPayload adds the payload to the get payment internal server error response
func (o *GetPaymentInternalServerError) WithPayload(payload *models.APIError) *GetPaymentInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get payment internal server error response
func (o *GetPaymentInternalServerError) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPaymentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
