// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/volmedo/pAPI/pkg/models"
)

// ListPaymentsOKCode is the HTTP code returned for type ListPaymentsOK
const ListPaymentsOKCode int = 200

/*ListPaymentsOK List of payment details

swagger:response listPaymentsOK
*/
type ListPaymentsOK struct {

	/*
	  In: Body
	*/
	Payload *models.PaymentDetailsListResponse `json:"body,omitempty"`
}

// NewListPaymentsOK creates ListPaymentsOK with default headers values
func NewListPaymentsOK() *ListPaymentsOK {

	return &ListPaymentsOK{}
}

// WithPayload adds the payload to the list payments o k response
func (o *ListPaymentsOK) WithPayload(payload *models.PaymentDetailsListResponse) *ListPaymentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list payments o k response
func (o *ListPaymentsOK) SetPayload(payload *models.PaymentDetailsListResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPaymentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListPaymentsBadRequestCode is the HTTP code returned for type ListPaymentsBadRequest
const ListPaymentsBadRequestCode int = 400

/*ListPaymentsBadRequest Bad Request

swagger:response listPaymentsBadRequest
*/
type ListPaymentsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewListPaymentsBadRequest creates ListPaymentsBadRequest with default headers values
func NewListPaymentsBadRequest() *ListPaymentsBadRequest {

	return &ListPaymentsBadRequest{}
}

// WithPayload adds the payload to the list payments bad request response
func (o *ListPaymentsBadRequest) WithPayload(payload *models.APIError) *ListPaymentsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list payments bad request response
func (o *ListPaymentsBadRequest) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPaymentsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListPaymentsTooManyRequestsCode is the HTTP code returned for type ListPaymentsTooManyRequests
const ListPaymentsTooManyRequestsCode int = 429

/*ListPaymentsTooManyRequests Too Many Requests

swagger:response listPaymentsTooManyRequests
*/
type ListPaymentsTooManyRequests struct {
}

// NewListPaymentsTooManyRequests creates ListPaymentsTooManyRequests with default headers values
func NewListPaymentsTooManyRequests() *ListPaymentsTooManyRequests {

	return &ListPaymentsTooManyRequests{}
}

// WriteResponse to the client
func (o *ListPaymentsTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(429)
}

// ListPaymentsInternalServerErrorCode is the HTTP code returned for type ListPaymentsInternalServerError
const ListPaymentsInternalServerErrorCode int = 500

/*ListPaymentsInternalServerError Internal Server Error

swagger:response listPaymentsInternalServerError
*/
type ListPaymentsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewListPaymentsInternalServerError creates ListPaymentsInternalServerError with default headers values
func NewListPaymentsInternalServerError() *ListPaymentsInternalServerError {

	return &ListPaymentsInternalServerError{}
}

// WithPayload adds the payload to the list payments internal server error response
func (o *ListPaymentsInternalServerError) WithPayload(payload *models.APIError) *ListPaymentsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list payments internal server error response
func (o *ListPaymentsInternalServerError) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPaymentsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
