// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListPaymentsParams creates a new ListPaymentsParams object
// with the default values initialized.
func NewListPaymentsParams() ListPaymentsParams {

	var (
		// initialize parameters with default values

		pageNumberDefault = int64(0)
		pageSizeDefault   = int64(10)
	)

	return ListPaymentsParams{
		PageNumber: &pageNumberDefault,

		PageSize: &pageSizeDefault,
	}
}

// ListPaymentsParams contains all the bound params for the list payments operation
// typically these are obtained from a http.Request
//
// swagger:parameters listPayments
type ListPaymentsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Which page to select
	  Minimum: 0
	  In: query
	  Default: 0
	*/
	PageNumber *int64
	/*Number of items per page
	  Maximum: 100
	  Minimum: 1
	  In: query
	  Default: 10
	*/
	PageSize *int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListPaymentsParams() beforehand.
func (o *ListPaymentsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qPageNumber, qhkPageNumber, _ := qs.GetOK("page[number]")
	if err := o.bindPageNumber(qPageNumber, qhkPageNumber, route.Formats); err != nil {
		res = append(res, err)
	}

	qPageSize, qhkPageSize, _ := qs.GetOK("page[size]")
	if err := o.bindPageSize(qPageSize, qhkPageSize, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPageNumber binds and validates parameter PageNumber from query.
func (o *ListPaymentsParams) bindPageNumber(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewListPaymentsParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("page[number]", "query", "int64", raw)
	}
	o.PageNumber = &value

	if err := o.validatePageNumber(formats); err != nil {
		return err
	}

	return nil
}

// validatePageNumber carries on validations for parameter PageNumber
func (o *ListPaymentsParams) validatePageNumber(formats strfmt.Registry) error {

	if err := validate.MinimumInt("page[number]", "query", int64(*o.PageNumber), 0, false); err != nil {
		return err
	}

	return nil
}

// bindPageSize binds and validates parameter PageSize from query.
func (o *ListPaymentsParams) bindPageSize(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewListPaymentsParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("page[size]", "query", "int64", raw)
	}
	o.PageSize = &value

	if err := o.validatePageSize(formats); err != nil {
		return err
	}

	return nil
}

// validatePageSize carries on validations for parameter PageSize
func (o *ListPaymentsParams) validatePageSize(formats strfmt.Registry) error {

	if err := validate.MinimumInt("page[size]", "query", int64(*o.PageSize), 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("page[size]", "query", int64(*o.PageSize), 100, false); err != nil {
		return err
	}

	return nil
}
